TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) test_signaler_stlib_polling.o
#extra stuff
OBJS+=	stm32f10x_gpio.o stm32f10x_rcc.o


# include common make file

include $(TEMPLATEROOT)/Makefile.common


